"""expand review items

Revision ID: f333316afad8
Revises: 9c76e8491952
Create Date: 2026-05-05 19:18:40.364796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f333316afad8'
down_revision: Union[str, Sequence[str], None] = '9c76e8491952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_items', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('review_items', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('review_items', sa.Column('severity', sa.String(length=50), nullable=False))
    op.add_column('review_items', sa.Column('citation_chunk_ids', sa.Text(), nullable=True))
    op.drop_column('review_items', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('review_items', 'citation_chunk_ids')
    op.drop_column('review_items', 'severity')
    op.drop_column('review_items', 'description')
    op.drop_column('review_items', 'title')
    # ### end Alembic commands ###
